---
name: "Syncron"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone repository"
        uses: actions/checkout@v3
      - name: "Setup Go"
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.17.0"
      - name: "Run linter - StaticCheck"
        uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1"
          install-go: false
      - name: Run Gosec Security Scanner
        uses: securego/gosec@master
        with:
          args:
            - ./...
            - -exlude G104
      - name: "Build syncron binary"
        run: go build -v -o .go/builds/syncron main.go
      - name: "Run tests - All"
        run: go test -v ./...
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3.3.1
      - name: "Publish artifacts - Binaries"
        uses: actions/upload-artifact@v3
        with:
          name: "Binaries"
          path: .go/builds
