---
name: "Syncron"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone repository"
        uses: actions/checkout@v3
      - name: "Setup Go"
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.17.0"
      - name: "Run linter - StaticCheck"
        uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1"
          install-go: false
      - name: "Build binary - Adhoc"
        run: go build -v -o .go/builds/adhoc cmd/adhoc/main.go
      - name: "Build binary - Server"
        run: go build -v -o .go/builds/server cmd/server/main.go
      - name: "Run tests - All"
        run: go test -v ./...
      - name: "Publish artifacts - Binaries"
        uses: actions/upload-artifact@v3
        with:
          name: "Binaries"
          path: .go/builds
