---
name: "Syncron"
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Clone repository"
        uses: actions/checkout@v3
      - name: "Setup Go"
        uses: actions/setup-go@v3
        with:
          go-version: ">=1.17.0"
      - name: "Run linter - StaticCheck"
        uses: dominikh/staticcheck-action@v1.2.0
        with:
          version: "2022.1"
          install-go: false
      - name: "Build binary - Server"
        run: go build -o .go/builds/server cmd/server.go
      - name: "Run tests - All"
        run: go test ./...
